name: Build ONNX runtimes
run-name: ONNX Models build

on:
  push:
    paths:
      - onnxruntime
      - onnxruntime-extensions
  workflow_dispatch:

jobs:
  build-android-runtime:
    runs-on: ubuntu-24.04
    name: Build Android ONNX runtime
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64-v8a, armeabi-v7a ]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager --update
          sdkmanager "platforms;android-35" "build-tools;35.0.0"
          sdkmanager --install "ndk;27.0.11718014" "cmake;3.31.1"

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        run: ./build.sh --use_extensions --use_nnapi --use_xnnpack --config Release --build_shared_lib --skip_tests --cmake_generator Ninja --build_dir build/Android --android --android_sdk_path "$ANDROID_HOME" --android_ndk_path "$ANDROID_HOME/ndk/27.0.11718014" --android_api 35 --android_abi ${{ matrix.arch }}

      - name: Compile onnxruntime-extensions
        working-directory: onnxruntime-extensions
        env:
          NDK_ROOT: "/usr/local/lib/android/sdk/ndk/27.0.11718014"
          ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"
          ANDROID_NDK_VERSION: "27.0.11718014"
          abi_name: ${{ matrix.arch }}
          ANDROID_API_LEVEL: "35"
        run: ./build.android

      - name: (Debug) list so
        run: find . -name "*.so"

      - uses: actions/upload-artifact@v4
        name: Upload built libonnxruntime library
        with:
          name: "libonnxruntime.${{ matrix.arch }}.1.20.1.so"
          path: "onnxruntime/build/Android/Release/libonnxruntime.so"
          if-no-files-found: error
          retention-days: 1

      - name: Copy runtime to repository
        run: |
          git pull
          cp -f onnxruntime/build/Android/Release/libonnxruntime.so android/src/main/jniLibs/${{ matrix.arch }}/libonnxruntime.1.20.1.so

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Built Android runtime
          file_pattern: '*.so'
          commit_user_name: Building Chad
          skip_checkout: false
          skip_fetch: false

  build-ios-runtime:
    runs-on: macos-15
    name: Build iOS ONNX runtime
    steps:
      - name: Reinstall brew
        run: |
          sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          sudo rm -fR /opt/homebrew
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/runner/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew install libpng cmake ccache
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        #run: ./build.sh --use_extensions --config Release --skip_tests --use_coreml --use_xcode --ios --apple_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 15 --cmake_generator Xcode
        run: ./build.sh --build_shared_lib --use_coreml --skip_tests --use_xnnpack --ios --apple_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 14 --use_xcode --config Release --parallel --use_binskim_compliant_compile_flags

      - name: (Debug) list dylibs
        run: find . -name "*.dylib"

      - uses: actions/upload-artifact@v4
        name: Upload built libonnxruntime library
        with:
          name: "libonnxruntime.1.20.1.dylib"
          path: "onnxruntime/build/iOS/Release/Release-iphoneos/libonnxruntime.1.20.1.dylib"
          if-no-files-found: error
          retention-days: 1

      - name: Copy runtime to repository
        run: |
          cp -f onnxruntime/build/iOS/Release/Release-iphoneos/libonnxruntime.1.20.1.dylib ios/libonnxruntime.1.20.1.dylib

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Built iOS runtime
          file_pattern: '*.dylib'
          commit_user_name: Building Chad
          skip_checkout: false
          skip_fetch: false

      - name: Compile onnxruntime-extensions
        working-directory: onnxruntime-extensions
        run: ./build.ios_xcframework --output_dir build/iOS-extensions --config Release --ios_deployment_target 13 --platform_arch iphoneos arm64 --mode build_platform_arch_frameworks_only -- --one_cmake_extra_define OCOS_ENABLE_SELECTED_OPLIST=ON

      - name: (Debug) list dylibs
        run: find . -name "*.dylib"

  build-macos-runtime:
    runs-on: macos-14
    name: Build MacOS ONNX runtime
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        run: ./build.sh --config Release --build_shared_lib --parallel --compile_no_warning_as_error --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64 --skip_tests

      - uses: actions/upload-artifact@v4
        name: Upload built libonnxruntime library
        with:
          name: "libonnxruntime.mac.1.20.1.dylib"
          path: "onnxruntime/build/MacOS/Release/libonnxruntime.1.20.1.dylib"
          if-no-files-found: error
          retention-days: 1

      - name: Copy runtime to repository
        run: |
          cp -f onnxruntime/build/MacOS/Release/libonnxruntime.1.20.1.dylib macos/libonnxruntime.1.20.1.dylib

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Built MacOS runtime
          file_pattern: '*.dylib'
          commit_user_name: Building Chad
          skip_checkout: false
          skip_fetch: false

  build-windows-runtime:
    runs-on: windows-2025
    name: Build Windows ONNX runtime
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        run: .\build.bat --config=Release --cmake_generator="Visual Studio 17 2022" --build_shared_lib --skip_tests

      - uses: actions/upload-artifact@v4
        name: Upload built libonnxruntime library
        with:
          name: "onnxruntime.1.20.1.dll"
          path: "onnxruntime/build/Windows/Release/Release/onnxruntime.dll"
          if-no-files-found: error
          retention-days: 1

      - name: Copy runtime to repository
        run: |
          Copy-Item -Force onnxruntime\build\Windows\Release\Release\onnxruntime.dll windows\onnxruntime.dll
          git pull

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Built Windows runtime
          file_pattern: '*.dll'
          commit_user_name: Building Chad
          skip_checkout: false
          skip_fetch: false
