name: Build ONNX runtimes
run-name: ONNX Models build

on:
  push:
    paths:
      - onnxruntime
      - onnxruntime-extensions
  workflow_dispatch:

jobs:
  build-android-runtime:
    runs-on: ubuntu-24.04
    name: Build Android ONNX runtime
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64-v8a, armeabi-v7a ]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager --update
          sdkmanager "platforms;android-35" "build-tools;35.0.0"
          sdkmanager --install "ndk;27.0.11718014" "cmake;3.31.1"

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        run: ./build.sh --use_extensions --use_nnapi --use_xnnpack --config Release --build_shared_lib --skip_tests --cmake_generator Ninja --build_dir build/Android --android --android_sdk_path "$ANDROID_HOME" --android_ndk_path "$ANDROID_HOME/ndk/27.0.11718014" --android_api 35 --android_abi ${{ matrix.arch }}

      - name: Compile onnxruntime-extensions
        working-directory: onnxruntime-extensions
        env:
          NDK_ROOT: "$ANDROID_HOME/ndk/27.0.11718014"
          ANDROID_SDK_ROOT: "$ANDROID_HOME"
          ANDROID_NDK_VERSION: "27.0.11718014"
          abi_name: ${{ matrix.arch }}
          ANDROID_API_LEVEL: "35"
        run: ./build.android

  build-ios-runtime:
    runs-on: macos-13
    name: Build iOS ONNX runtime
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile onnxruntime
        working-directory: onnxruntime
        run: ./build.sh --use_extensions --config Release --skip_tests --use_coreml --use_xcode --ios --apple_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 15 --cmake_generator Xcode

      - name: (Debug) list dylibs
        run: find . -name "*.dylib"

      - name: Compile onnxruntime-extensions
        working-directory: onnxruntime-extensions
        run: ./build.ios_xcframework
