name: Build ONNX runtimes
run-name: ONNX Models build

on:
  push:
    paths:
      - onnxruntime
      - onnxruntime-extensions
  workflow_dispatch:

jobs:
  build-android-runtime:
    runs-on: ubuntu-24.04
    name: Build Android ONNX runtime
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager --update
          sdkmanager "platforms;android-35" "build-tools;35.0.0"
          sdkmanager --install "ndk;27.0.11718014" "cmake;3.31.1"

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile
        working-directory: onnxruntime
        run: ./build.sh --use_extensions --use_nnapi --use_xnnpack --config Release --build_shared_lib --skip_tests --cmake_generator Ninja --build_dir build/Android --android --android_sdk_path "$ANDROID_HOME" --android_ndk_path "$ANDROID_HOME/ndk/27.0.11718014" --android_api 35 --android_abi arm64-v8a